// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Arena = __t.object("Arena", {
  id: __t.string(),
  phase: __t.string(),
  elapsed: __t.f64(),
  radius: __t.f64(),
  winner: __t.string(),
  round: __t.u32(),
});
export type Arena = __Infer<typeof Arena>;

export const Clock = __t.object("Clock", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type Clock = __Infer<typeof Clock>;

export const District = __t.object("District", {
  id: __t.string(),
  get damage() {
    return __t.array(ObjectDamage);
  },
});
export type District = __Infer<typeof District>;

export const Event = __t.object("Event", {
  id: __t.u64(),
  room: __t.string(),
  payload: __t.string(),
  expires: __t.u64(),
});
export type Event = __Infer<typeof Event>;

export const ObjectDamage = __t.object("ObjectDamage", {
  id: __t.string(),
  amount: __t.f64(),
});
export type ObjectDamage = __Infer<typeof ObjectDamage>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  hero: __t.u32(),
  room: __t.string(),
  state: __t.string(),
  input: __t.string(),
  lastInput: __t.u64(),
});
export type Player = __Infer<typeof Player>;
