// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ControlReducer from "../control_reducer";
import JoinReducer from "../join_reducer";
import LeaveReducer from "../leave_reducer";
import StartRoundReducer from "../start_round_reducer";

export type ControlParams = __Infer<typeof ControlReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type LeaveParams = __Infer<typeof LeaveReducer>;
export type StartRoundParams = __Infer<typeof StartRoundReducer>;
